name: iManager
main: imanager\iManager
version: 1.2.0
api: [1.12.0, 2.0.0]
load: STARTUP
author: Gamecrafter
description: Manage your server like never before!
website: https://github.com/Viperize/iManager-PocketMine
permissions:
 imanager:
  default: op
  children:
   imanager.command:
    default: op
    children:
     imanager.command.imanager:
      default: op
